### ISSUE TITLE
Never receive the status event with code "started"

### ISSUE THREAD

**Issue by rubel** [rainbowcreatures/FlashyWrappers#8] opened 2016-10-21 03:42 UTC
package  {

```
import flash.display.MovieClip;
import com.rainbowcreatures.*;
import com.rainbowcreatures.swf.*;
import flash.events.StatusEvent; // in case you're not importing this already
import flash.events.Event; // in case you're not importing this already
import flash.events.IOErrorEvent;
import flash.utils.ByteArray;
import flash.net.FileReference;
import flash.text.TextField;
import flash.text.TextFormat;
import flash.events.MouseEvent;
import flash.system.Security;
import flash.utils.setTimeout;

[SWF(width=320,height=320, frameRate='24')]     
public class Helloworld extends MovieClip {

    var myEncoder:FWVideoEncoder;
    var frameIndex:Number = 0;
    var maxFrames:Number = 50;
    var txt:TextField = new TextField();

    public function Helloworld() {
        // constructor code
        //Security.allowDomain("*");
        //Security.loadPolicyFile("http://hamzagames.com/crossdomain.xml");
        var tf:TextFormat = new TextFormat("Arial", 30, 0XAA5050);
        txt.text = "Hello world!";          
        txt.setTextFormat(tf);
        txt.width = 200;
        txt.y = 180;
        addChild(txt);


        myEncoder = FWVideoEncoder.getInstance(this);   
        myEncoder.addEventListener(StatusEvent.STATUS, onStatus);
        //myEncoder.load("http://hamzagames.com/easy_sketch_pro/lib/FlashPlayer/mp4/");

        myEncoder.load("../../lib/FlashPlayer/mp4/");
    }
    function saveVid(e:MouseEvent):void{
        var bo:ByteArray = myEncoder.getVideo();
        log("Recording finished, video length: " + bo.length);                              

        // save the file for check
        var saveFile:FileReference = new FileReference();
        saveFile.addEventListener(Event.COMPLETE, saveCompleteHandler);
        saveFile.addEventListener(IOErrorEvent.IO_ERROR, saveIOErrorHandler);
        saveFile.save(bo, "video.mp4");                             
    }

    private function onStatus(e:StatusEvent):void {
        log("Got status event: " + e.code+e);
        if (e.code == "ready") {
            if (myEncoder.platform == FWVideoEncoder.PLATFORM_FLASH) {
                trace('platform is flash so changing dimensions.............400x300');
                myEncoder.setDimensions(400, 300);
            }
            myEncoder.start(20, FWVideoEncoder.AUDIO_MICROPHONE);
        }

        // FW was started
        if (e.code == "started") {
            log('........................started..............................');
            // add frame listener - start sending frames
            addEventListener(Event.ENTER_FRAME, onFrame);
        }
    }

    private function onFrame(e:Event):void {
        // animate the rectangle
        txt.x++;

        // clear the background, otherwise all transparency will be black by default in the video
        graphics.beginFill(0XFF0000, 1);
        graphics.drawRect(0, 0, stage.stageWidth, stage.stageHeight);
        graphics.endFill();

        // render one frame of your stuff into someMovieClip, then capture and
        // add one frame into the FlashyWrappers video encoder like this:
        myEncoder.capture(this);
        frameIndex++;
        if (frameIndex >= maxFrames - 1) {
            removeEventListener(Event.ENTER_FRAME, onFrame);                
            myEncoder.finish();
        }
    }                           

    // file was saved
    private function saveCompleteHandler(e:Event):void {
        log("Video saved!");
    }

    // some error happened
    private function saveIOErrorHandler(e:IOErrorEvent):void {
        log("Video NOT saved:(");
    }

    private function log(msg:String):void{
        logtxt.text = logtxt.text+'\n'+msg;
        trace(msg);
    }

}   
```

}

**Comment by rainbowcreatures** [comment] 2016-11-13 08:40
Duplicate of #9

**Closed by rainbowcreatures** 2016-11-13 08:40 UTC
