### ISSUE TITLE
Error creating build iOS ane

### ISSUE THREAD

**Issue by drewand** [rainbowcreatures/FlashyWrappers#47] opened 2018-06-05 04:52 UTC
Hi, I'm currently testing the ane for iOS and i am getting build error written:
"Address not in any section for architecture arm64"

Android can build successfully with the ane for Android.

I tried building with air sdk 25 to 29 ios keeps failing. Im using adobe animate cc

Can admin help me on this problem?

Thanks

**Comment by vorlovsky** [comment] 2018-06-05 09:49
99,9% sure it's not related to the FlashWrappers ANE.
I can see complains about Citrus engine producing the same issue - can't it be the cause?

**Comment by drewand** [comment] 2018-06-06 14:06
I think it is, 
I have no problem with Android FlashWrappers ANE,
I am facing problem iOS FlashWrappers ANE.

**Comment by vorlovsky** [comment] 2018-06-06 16:00
OK. Just a few questions:
1. Are you trying to build an app or an ANE itself?
Then for the 1st case:
2. Do you use Citrus engine in your app?
3. Does your app fail on debug build also?
4. Overall - what's the reason to blame on the FW ANE?

**Comment by drewand** [comment] 2018-06-07 00:32
Thanks for replying:
1. Im trying to build an iOS app

2. No I'm not using Citrus Engine

3. Debug build as in you mean running it on adobe animate cc? If that is what u mean, yes it works only when i use your Desktop ANE

4. I have successfully build my apps on Android, Windows with flashywrapper ANE? except for iOS. When i remove your iOS ANE dependency my iOS app build successfully without your flashywrapper service.

Is there anyway you can help me on this?
I have tested Android devices and it is working amazingly.  I have to test on iOS devices before I can decide to purchase this comercial version.

Thanks for your time!

**Comment by vorlovsky** [comment] 2018-06-07 13:28
To make things clear - unfortunately, I'm not a guy from the FW team, I'm just a developer who used this ANE in some (iOS-only) projects. Speaking about 3 - I have meant to select debugging IPA as a deployment type.

**Comment by drewand** [comment] 2018-06-07 15:17
Ah I see, let me try selecting debugging IPA. Are you using adobe animate CC as well?

**Comment by drewand** [comment] 2018-06-07 15:23
vorlovsky Selecting debugging IPA Works! Thanks!

**Comment by vorlovsky** [comment] 2018-06-07 16:42
At least it's a workaround. But you'll not be able to push such IPA to Apple Store.

**Comment by drewand** [comment] 2018-06-08 07:22
I manage the output production build. Only problem i face outputting ipa was selecting device testing.

**Comment by rainbowcreatures** [comment] 2018-06-10 08:34
Hey drewand, I'm the author of FW. Thanks Vyacheslav for chiming in for this! Sorry for spotting the thread late, people don't post issues to GitHub nowadays, mostly they e-mail me directly. 

I'll test FW for iOS later today to see if this is might be something related to iOS 11. Might need to rebuild it with the latest SDK.

It's true that according to what Vyacheslav wrote, I've googled this exact same issue in relation to other libraries, ANE's...even Starling (they can also make debug work, but not release):

https://forum.starling-framework.org/topic/error-address-not-in-any-section-for-architecture-arm64

It might not be related though. Also important  - make sure to try building the sample (FWExampleCamera) first to rule out anything in your app. Anyway will get back to you later today after I make the tests.

**Comment by rainbowcreatures** [comment] 2018-06-11 17:22
I was able to build IPA's with FW 2.6 in Animate CC for Windows, using AIR 27.0.0.124 in Debug, Ad Hoc and App Store build modes without any linker errors. I used FWExampleCamera app. 

Not sure what your app does, but as I meantioned earlier, try to build the example app first to see if you can reproduce your build issue, to rule out anything app related.

**Comment by drewand** [comment] 2018-06-19 04:58
Hi Rainbow, thanks for the info i'm currently building for iOS will surely inform you the updates.

In the meant time i found out your full version of 2.6 doesnt have android ane. can i u send to me.
I bought your sdk recently

**Comment by rainbowcreatures** [comment] 2018-07-02 09:22
We resolved this already over email, closing.

**Closed as completed by rainbowcreatures** 2018-07-02 09:22 UTC
