### ISSUE TITLE
Error #3500: The extension context does not have a method with the name fw_ffmpeg_create.

### ISSUE THREAD

**Issue by cavabaja** [rainbowcreatures/FlashyWrappers#31] opened 2017-08-28 16:37 UTC
Hi,

I am trying to make an example of video recording in an Air application. I added the FWEncoderANE64.ane ( i compiled with an iMac 64 ) file and copied the sample code from the PDF document.
I work with the Adobe CC 2015 and Adobe Air 26.0.0.118 for desktop and Free version of FlashyWrappers 2.55. I'm trying to test and if all works fine buy a licence for a big project.

When the myEncoder.start () method is called, the following error appears:

ArgumentError: Error #3500: The extension context does not have a method with the name fw_ffmpeg_create.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.rainbowcreatures::FWVideoEncoder/start()[/Users/apple/Desktop/Flash_Native_Extensions/FlashyWrappers_SVN/rainbowcreatures_flashywrappers/FW_src_stable/com/rainbowcreatures/FWVideoEncoder.as:1590]
	at main_fla::MainTimeline/onStatus()[main_fla.MainTimeline::frame1:23]
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at com.rainbowcreatures::FWVideoEncoder/load()[/Users/apple/Desktop/Flash_Native_Extensions/FlashyWrappers_SVN/rainbowcreatures_flashywrappers/FW_src_stable/com/rainbowcreatures/FWVideoEncoder.as:1153]
	at main_fla::MainTimeline/frame1()[main_fla.MainTimeline::frame1:12]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at ADLAppEntry/run()
	at global/runtime::ADLEntry()

**Comment by rainbowcreatures** [comment] 2017-09-06 13:57
This is unfortunately a typical issue of FW ANE for OS X. It is caused by the symlinks inside the ANE, they are not properly resolved when Adobe IDE's unzip the ANE to temporary folder. As a workaround FW 2.6 just copies the needed files multiple times, replacing the symlinks, which makes the ANE a bit larger, but should get rid of the error. 

Until FW 2.6 is released, I can send you a free version of the OS X build - please get in touch via the website contact form or ping here again if there is no response.

**Comment by cavabaja** [comment] 2017-09-07 16:55
Hello!
thank you, i will do it!

**Comment by rainbowcreatures** [comment] 2018-01-05 15:44
Note, for FW2.6 this should be fixed now with a special ANE provided in the package (with no symlinks). That one should hopefully build fine in side IDE's.

**Closed as completed by rainbowcreatures** 2018-01-05 15:44 UTC

**Comment by renaudcollet** [comment] 2018-05-14 14:58
Hi, I use the FW 2.6 ANE with Animate CC on Windows 64, I have the same error.
Do you have an idea ?

> 
ArgumentError: Error #3500: The extension context does not have a method with the name fw_ffmpeg_create.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.rainbowcreatures::FWVideoEncoder/start()[C:\Documents and Settings\Pavel\Documents\FlashyWrappers\AS3\com\rainbowcreatures\FWVideoEncoder.as:1471]

>

**Comment by rainbowcreatures** [comment] 2018-05-20 19:15
Usually this happens when the native portion of the ANE isn't included correctly, when building. Then, the first native method FW tries to use is not found (the first one is always fw_ffmpeg_create), resulting in the error you are seeing. 

I'm not ruling out other causes, but please make double sure the ANE is included properly, including in the application XML file.
